services:
  mongodb:
    image: mongo:latest
    container_name: mern_catalog_db
    restart: always
    ports:
      - '${MONGO_PORT}:${MONGO_PORT}'
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
    volumes:
      - mern_catalog_data:/data/db

volumes:
  mern_catalog_data:
